# See https://github.com/dart-lang/mono_repo for details
dart:
- 2.4.0
- dev

stages:
- smoke_test:
  - group:
    - dartfmt
    - dartanalyzer: --fatal-infos --fatal-warnings .
    dart: [dev]
  - group:
    - dartanalyzer: --fatal-warnings .
    dart: [2.4.0]
- unit_test:
  - group:
    - test
