name: stopwatch
description: A sample application

dependencies:
  polymer: ^1.0.0
  web_components: ^0.12.0
  browser: ^0.10.0
  reflectable: ^0.3.0
transformers:
- web_components:
    entry_points:
    - web/index.html
- reflectable:
    entry_points:
    - web/index.dart
environment:
  sdk: ">=1.2.0 <2.0.0"

dependency_overrides:
  polymer:
    git:
      ref: 1.0.0-rc.2
      url: https://github.com/dart-lang/polymer-dart.git
  polymer_interop:
    git:
      ref: 0.2.0-dev
      url: https://github.com/dart-lang/polymer_interop.git

homepage: https://www.dartlang.org/docs/tutorials/polymer-intro/
